# Generated by Django 3.0 on 2022-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joined',
            name='dues',
            field=models.IntegerField(default=0),
        ),
    ]
